filter:
  paths:
      - src/

before_commands:
  - 'composer install --no-interaction --prefer-source'

tools:
  php_code_sniffer:
      config:
          standard: PSR2
  php_code_coverage:
      enabled: true
  php_loc: true
  php_analyzer: true
  php_pdepend: true